# Generated by Django 4.2.2 on 2023-06-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=50)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
